[package]
name = "delaunay"
version = "0.1.0"
authors = ["takagi <qtg.apple480.21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "1.0"
rand = "0.7"
